// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: pkg/proto/common.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RetryPolicy struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	MaxAttempts          int32                  `protobuf:"varint,1,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	InitialBackoff       *durationpb.Duration   `protobuf:"bytes,2,opt,name=initial_backoff,json=initialBackoff,proto3" json:"initial_backoff,omitempty"`
	MaxBackoff           *durationpb.Duration   `protobuf:"bytes,3,opt,name=max_backoff,json=maxBackoff,proto3" json:"max_backoff,omitempty"`
	BackoffMultiplier    float64                `protobuf:"fixed64,4,opt,name=backoff_multiplier,json=backoffMultiplier,proto3" json:"backoff_multiplier,omitempty"`
	RetryableStatusCodes []string               `protobuf:"bytes,5,rep,name=retryable_status_codes,json=retryableStatusCodes,proto3" json:"retryable_status_codes,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RetryPolicy) Reset() {
	*x = RetryPolicy{}
	mi := &file_pkg_proto_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryPolicy) ProtoMessage() {}

func (x *RetryPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryPolicy.ProtoReflect.Descriptor instead.
func (*RetryPolicy) Descriptor() ([]byte, []int) {
	return file_pkg_proto_common_proto_rawDescGZIP(), []int{0}
}

func (x *RetryPolicy) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *RetryPolicy) GetInitialBackoff() *durationpb.Duration {
	if x != nil {
		return x.InitialBackoff
	}
	return nil
}

func (x *RetryPolicy) GetMaxBackoff() *durationpb.Duration {
	if x != nil {
		return x.MaxBackoff
	}
	return nil
}

func (x *RetryPolicy) GetBackoffMultiplier() float64 {
	if x != nil {
		return x.BackoffMultiplier
	}
	return 0
}

func (x *RetryPolicy) GetRetryableStatusCodes() []string {
	if x != nil {
		return x.RetryableStatusCodes
	}
	return nil
}

type CircuitBreakerConfig struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MaxRequests         int32                  `protobuf:"varint,1,opt,name=max_requests,json=maxRequests,proto3" json:"max_requests,omitempty"`
	Interval            *durationpb.Duration   `protobuf:"bytes,2,opt,name=interval,proto3" json:"interval,omitempty"`
	Timeout             *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	ConsecutiveFailures int32                  `protobuf:"varint,4,opt,name=consecutive_failures,json=consecutiveFailures,proto3" json:"consecutive_failures,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CircuitBreakerConfig) Reset() {
	*x = CircuitBreakerConfig{}
	mi := &file_pkg_proto_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CircuitBreakerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CircuitBreakerConfig) ProtoMessage() {}

func (x *CircuitBreakerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CircuitBreakerConfig.ProtoReflect.Descriptor instead.
func (*CircuitBreakerConfig) Descriptor() ([]byte, []int) {
	return file_pkg_proto_common_proto_rawDescGZIP(), []int{1}
}

func (x *CircuitBreakerConfig) GetMaxRequests() int32 {
	if x != nil {
		return x.MaxRequests
	}
	return 0
}

func (x *CircuitBreakerConfig) GetInterval() *durationpb.Duration {
	if x != nil {
		return x.Interval
	}
	return nil
}

func (x *CircuitBreakerConfig) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *CircuitBreakerConfig) GetConsecutiveFailures() int32 {
	if x != nil {
		return x.ConsecutiveFailures
	}
	return 0
}

type RateLimitConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequestsPerSecond int32                  `protobuf:"varint,1,opt,name=requests_per_second,json=requestsPerSecond,proto3" json:"requests_per_second,omitempty"`
	Burst             int32                  `protobuf:"varint,2,opt,name=burst,proto3" json:"burst,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RateLimitConfig) Reset() {
	*x = RateLimitConfig{}
	mi := &file_pkg_proto_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitConfig) ProtoMessage() {}

func (x *RateLimitConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitConfig.ProtoReflect.Descriptor instead.
func (*RateLimitConfig) Descriptor() ([]byte, []int) {
	return file_pkg_proto_common_proto_rawDescGZIP(), []int{2}
}

func (x *RateLimitConfig) GetRequestsPerSecond() int32 {
	if x != nil {
		return x.RequestsPerSecond
	}
	return 0
}

func (x *RateLimitConfig) GetBurst() int32 {
	if x != nil {
		return x.Burst
	}
	return 0
}

type ServiceConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Endpoint       string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Timeout        *durationpb.Duration   `protobuf:"bytes,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	RetryPolicy    *RetryPolicy           `protobuf:"bytes,5,opt,name=retry_policy,json=retryPolicy,proto3" json:"retry_policy,omitempty"`
	CircuitBreaker *CircuitBreakerConfig  `protobuf:"bytes,6,opt,name=circuit_breaker,json=circuitBreaker,proto3" json:"circuit_breaker,omitempty"`
	RateLimit      *RateLimitConfig       `protobuf:"bytes,7,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ServiceConfig) Reset() {
	*x = ServiceConfig{}
	mi := &file_pkg_proto_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceConfig) ProtoMessage() {}

func (x *ServiceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceConfig.ProtoReflect.Descriptor instead.
func (*ServiceConfig) Descriptor() ([]byte, []int) {
	return file_pkg_proto_common_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ServiceConfig) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *ServiceConfig) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *ServiceConfig) GetRetryPolicy() *RetryPolicy {
	if x != nil {
		return x.RetryPolicy
	}
	return nil
}

func (x *ServiceConfig) GetCircuitBreaker() *CircuitBreakerConfig {
	if x != nil {
		return x.CircuitBreaker
	}
	return nil
}

func (x *ServiceConfig) GetRateLimit() *RateLimitConfig {
	if x != nil {
		return x.RateLimit
	}
	return nil
}

func (x *ServiceConfig) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_pkg_proto_common_proto protoreflect.FileDescriptor

const file_pkg_proto_common_proto_rawDesc = "" +
	"\n" +
	"\x16pkg/proto/common.proto\x12\n" +
	"maestro.v1\x1a\x1egoogle/protobuf/duration.proto\"\x95\x02\n" +
	"\vRetryPolicy\x12!\n" +
	"\fmax_attempts\x18\x01 \x01(\x05R\vmaxAttempts\x12B\n" +
	"\x0finitial_backoff\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x0einitialBackoff\x12:\n" +
	"\vmax_backoff\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\n" +
	"maxBackoff\x12-\n" +
	"\x12backoff_multiplier\x18\x04 \x01(\x01R\x11backoffMultiplier\x124\n" +
	"\x16retryable_status_codes\x18\x05 \x03(\tR\x14retryableStatusCodes\"\xd8\x01\n" +
	"\x14CircuitBreakerConfig\x12!\n" +
	"\fmax_requests\x18\x01 \x01(\x05R\vmaxRequests\x125\n" +
	"\binterval\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\binterval\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x121\n" +
	"\x14consecutive_failures\x18\x04 \x01(\x05R\x13consecutiveFailures\"W\n" +
	"\x0fRateLimitConfig\x12.\n" +
	"\x13requests_per_second\x18\x01 \x01(\x05R\x11requestsPerSecond\x12\x14\n" +
	"\x05burst\x18\x02 \x01(\x05R\x05burst\"\xcd\x03\n" +
	"\rServiceConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x123\n" +
	"\atimeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12:\n" +
	"\fretry_policy\x18\x05 \x01(\v2\x17.maestro.v1.RetryPolicyR\vretryPolicy\x12I\n" +
	"\x0fcircuit_breaker\x18\x06 \x01(\v2 .maestro.v1.CircuitBreakerConfigR\x0ecircuitBreaker\x12:\n" +
	"\n" +
	"rate_limit\x18\a \x01(\v2\x1b.maestro.v1.RateLimitConfigR\trateLimit\x12C\n" +
	"\bmetadata\x18\b \x03(\v2'.maestro.v1.ServiceConfig.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B/Z-github.com/maestro/maestro.go/pkg/proto;protob\x06proto3"

var (
	file_pkg_proto_common_proto_rawDescOnce sync.Once
	file_pkg_proto_common_proto_rawDescData []byte
)

func file_pkg_proto_common_proto_rawDescGZIP() []byte {
	file_pkg_proto_common_proto_rawDescOnce.Do(func() {
		file_pkg_proto_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_common_proto_rawDesc), len(file_pkg_proto_common_proto_rawDesc)))
	})
	return file_pkg_proto_common_proto_rawDescData
}

var file_pkg_proto_common_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_proto_common_proto_goTypes = []any{
	(*RetryPolicy)(nil),          // 0: maestro.v1.RetryPolicy
	(*CircuitBreakerConfig)(nil), // 1: maestro.v1.CircuitBreakerConfig
	(*RateLimitConfig)(nil),      // 2: maestro.v1.RateLimitConfig
	(*ServiceConfig)(nil),        // 3: maestro.v1.ServiceConfig
	nil,                          // 4: maestro.v1.ServiceConfig.MetadataEntry
	(*durationpb.Duration)(nil),  // 5: google.protobuf.Duration
}
var file_pkg_proto_common_proto_depIdxs = []int32{
	5, // 0: maestro.v1.RetryPolicy.initial_backoff:type_name -> google.protobuf.Duration
	5, // 1: maestro.v1.RetryPolicy.max_backoff:type_name -> google.protobuf.Duration
	5, // 2: maestro.v1.CircuitBreakerConfig.interval:type_name -> google.protobuf.Duration
	5, // 3: maestro.v1.CircuitBreakerConfig.timeout:type_name -> google.protobuf.Duration
	5, // 4: maestro.v1.ServiceConfig.timeout:type_name -> google.protobuf.Duration
	0, // 5: maestro.v1.ServiceConfig.retry_policy:type_name -> maestro.v1.RetryPolicy
	1, // 6: maestro.v1.ServiceConfig.circuit_breaker:type_name -> maestro.v1.CircuitBreakerConfig
	2, // 7: maestro.v1.ServiceConfig.rate_limit:type_name -> maestro.v1.RateLimitConfig
	4, // 8: maestro.v1.ServiceConfig.metadata:type_name -> maestro.v1.ServiceConfig.MetadataEntry
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_pkg_proto_common_proto_init() }
func file_pkg_proto_common_proto_init() {
	if File_pkg_proto_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_common_proto_rawDesc), len(file_pkg_proto_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_common_proto_goTypes,
		DependencyIndexes: file_pkg_proto_common_proto_depIdxs,
		MessageInfos:      file_pkg_proto_common_proto_msgTypes,
	}.Build()
	File_pkg_proto_common_proto = out.File
	file_pkg_proto_common_proto_goTypes = nil
	file_pkg_proto_common_proto_depIdxs = nil
}
