// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: pkg/proto/maestro.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkflowStatus int32

const (
	WorkflowStatus_WORKFLOW_STATUS_UNKNOWN      WorkflowStatus = 0
	WorkflowStatus_WORKFLOW_STATUS_PENDING      WorkflowStatus = 1
	WorkflowStatus_WORKFLOW_STATUS_RUNNING      WorkflowStatus = 2
	WorkflowStatus_WORKFLOW_STATUS_SUCCESS      WorkflowStatus = 3
	WorkflowStatus_WORKFLOW_STATUS_FAILED       WorkflowStatus = 4
	WorkflowStatus_WORKFLOW_STATUS_CANCELLED    WorkflowStatus = 5
	WorkflowStatus_WORKFLOW_STATUS_COMPENSATING WorkflowStatus = 6
	WorkflowStatus_WORKFLOW_STATUS_COMPENSATED  WorkflowStatus = 7
)

// Enum value maps for WorkflowStatus.
var (
	WorkflowStatus_name = map[int32]string{
		0: "WORKFLOW_STATUS_UNKNOWN",
		1: "WORKFLOW_STATUS_PENDING",
		2: "WORKFLOW_STATUS_RUNNING",
		3: "WORKFLOW_STATUS_SUCCESS",
		4: "WORKFLOW_STATUS_FAILED",
		5: "WORKFLOW_STATUS_CANCELLED",
		6: "WORKFLOW_STATUS_COMPENSATING",
		7: "WORKFLOW_STATUS_COMPENSATED",
	}
	WorkflowStatus_value = map[string]int32{
		"WORKFLOW_STATUS_UNKNOWN":      0,
		"WORKFLOW_STATUS_PENDING":      1,
		"WORKFLOW_STATUS_RUNNING":      2,
		"WORKFLOW_STATUS_SUCCESS":      3,
		"WORKFLOW_STATUS_FAILED":       4,
		"WORKFLOW_STATUS_CANCELLED":    5,
		"WORKFLOW_STATUS_COMPENSATING": 6,
		"WORKFLOW_STATUS_COMPENSATED":  7,
	}
)

func (x WorkflowStatus) Enum() *WorkflowStatus {
	p := new(WorkflowStatus)
	*p = x
	return p
}

func (x WorkflowStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_maestro_proto_enumTypes[0].Descriptor()
}

func (WorkflowStatus) Type() protoreflect.EnumType {
	return &file_pkg_proto_maestro_proto_enumTypes[0]
}

func (x WorkflowStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowStatus.Descriptor instead.
func (WorkflowStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_maestro_proto_rawDescGZIP(), []int{0}
}

type StepState int32

const (
	StepState_STEP_STATE_UNKNOWN      StepState = 0
	StepState_STEP_STATE_PENDING      StepState = 1
	StepState_STEP_STATE_RUNNING      StepState = 2
	StepState_STEP_STATE_SUCCESS      StepState = 3
	StepState_STEP_STATE_FAILED       StepState = 4
	StepState_STEP_STATE_SKIPPED      StepState = 5
	StepState_STEP_STATE_COMPENSATING StepState = 6
	StepState_STEP_STATE_COMPENSATED  StepState = 7
)

// Enum value maps for StepState.
var (
	StepState_name = map[int32]string{
		0: "STEP_STATE_UNKNOWN",
		1: "STEP_STATE_PENDING",
		2: "STEP_STATE_RUNNING",
		3: "STEP_STATE_SUCCESS",
		4: "STEP_STATE_FAILED",
		5: "STEP_STATE_SKIPPED",
		6: "STEP_STATE_COMPENSATING",
		7: "STEP_STATE_COMPENSATED",
	}
	StepState_value = map[string]int32{
		"STEP_STATE_UNKNOWN":      0,
		"STEP_STATE_PENDING":      1,
		"STEP_STATE_RUNNING":      2,
		"STEP_STATE_SUCCESS":      3,
		"STEP_STATE_FAILED":       4,
		"STEP_STATE_SKIPPED":      5,
		"STEP_STATE_COMPENSATING": 6,
		"STEP_STATE_COMPENSATED":  7,
	}
)

func (x StepState) Enum() *StepState {
	p := new(StepState)
	*p = x
	return p
}

func (x StepState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StepState) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_maestro_proto_enumTypes[1].Descriptor()
}

func (StepState) Type() protoreflect.EnumType {
	return &file_pkg_proto_maestro_proto_enumTypes[1]
}

func (x StepState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StepState.Descriptor instead.
func (StepState) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_maestro_proto_rawDescGZIP(), []int{1}
}

type EventType int32

const (
	EventType_EVENT_TYPE_UNKNOWN                EventType = 0
	EventType_EVENT_TYPE_WORKFLOW_STARTED       EventType = 1
	EventType_EVENT_TYPE_WORKFLOW_COMPLETED     EventType = 2
	EventType_EVENT_TYPE_WORKFLOW_FAILED        EventType = 3
	EventType_EVENT_TYPE_STEP_STARTED           EventType = 4
	EventType_EVENT_TYPE_STEP_COMPLETED         EventType = 5
	EventType_EVENT_TYPE_STEP_FAILED            EventType = 6
	EventType_EVENT_TYPE_STEP_RETRY             EventType = 7
	EventType_EVENT_TYPE_COMPENSATION_STARTED   EventType = 8
	EventType_EVENT_TYPE_COMPENSATION_COMPLETED EventType = 9
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNKNOWN",
		1: "EVENT_TYPE_WORKFLOW_STARTED",
		2: "EVENT_TYPE_WORKFLOW_COMPLETED",
		3: "EVENT_TYPE_WORKFLOW_FAILED",
		4: "EVENT_TYPE_STEP_STARTED",
		5: "EVENT_TYPE_STEP_COMPLETED",
		6: "EVENT_TYPE_STEP_FAILED",
		7: "EVENT_TYPE_STEP_RETRY",
		8: "EVENT_TYPE_COMPENSATION_STARTED",
		9: "EVENT_TYPE_COMPENSATION_COMPLETED",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNKNOWN":                0,
		"EVENT_TYPE_WORKFLOW_STARTED":       1,
		"EVENT_TYPE_WORKFLOW_COMPLETED":     2,
		"EVENT_TYPE_WORKFLOW_FAILED":        3,
		"EVENT_TYPE_STEP_STARTED":           4,
		"EVENT_TYPE_STEP_COMPLETED":         5,
		"EVENT_TYPE_STEP_FAILED":            6,
		"EVENT_TYPE_STEP_RETRY":             7,
		"EVENT_TYPE_COMPENSATION_STARTED":   8,
		"EVENT_TYPE_COMPENSATION_COMPLETED": 9,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_maestro_proto_enumTypes[2].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_pkg_proto_maestro_proto_enumTypes[2]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_maestro_proto_rawDescGZIP(), []int{2}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pkg_proto_maestro_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_maestro_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pkg_proto_maestro_proto_rawDescGZIP(), []int{0}
}

type ExecuteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WorkflowName   string                 `protobuf:"bytes,1,opt,name=workflow_name,json=workflowName,proto3" json:"workflow_name,omitempty"`
	Input          *structpb.Struct       `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_pkg_proto_maestro_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_maestro_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_maestro_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteRequest) GetWorkflowName() string {
	if x != nil {
		return x.WorkflowName
	}
	return ""
}

func (x *ExecuteRequest) GetInput() *structpb.Struct {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ExecuteRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ExecuteRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Status        WorkflowStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=maestro.v1.WorkflowStatus" json:"status,omitempty"`
	Output        *structpb.Struct       `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_pkg_proto_maestro_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_maestro_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_maestro_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteResponse) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *ExecuteResponse) GetStatus() WorkflowStatus {
	if x != nil {
		return x.Status
	}
	return WorkflowStatus_WORKFLOW_STATUS_UNKNOWN
}

func (x *ExecuteResponse) GetOutput() *structpb.Struct {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecuteResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ExecuteResponse) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type ExecuteEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	StepId        string                 `protobuf:"bytes,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Type          EventType              `protobuf:"varint,3,opt,name=type,proto3,enum=maestro.v1.EventType" json:"type,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteEvent) Reset() {
	*x = ExecuteEvent{}
	mi := &file_pkg_proto_maestro_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteEvent) ProtoMessage() {}

func (x *ExecuteEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_maestro_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteEvent.ProtoReflect.Descriptor instead.
func (*ExecuteEvent) Descriptor() ([]byte, []int) {
	return file_pkg_proto_maestro_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteEvent) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *ExecuteEvent) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *ExecuteEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNKNOWN
}

func (x *ExecuteEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecuteEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ExecuteEvent) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_pkg_proto_maestro_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_maestro_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_maestro_proto_rawDescGZIP(), []int{4}
}

func (x *StatusRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Status        WorkflowStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=maestro.v1.WorkflowStatus" json:"status,omitempty"`
	Steps         []*StepStatus          `protobuf:"bytes,3,rep,name=steps,proto3" json:"steps,omitempty"`
	Output        *structpb.Struct       `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_pkg_proto_maestro_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_maestro_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_maestro_proto_rawDescGZIP(), []int{5}
}

func (x *StatusResponse) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *StatusResponse) GetStatus() WorkflowStatus {
	if x != nil {
		return x.Status
	}
	return WorkflowStatus_WORKFLOW_STATUS_UNKNOWN
}

func (x *StatusResponse) GetSteps() []*StepStatus {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *StatusResponse) GetOutput() *structpb.Struct {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *StatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_pkg_proto_maestro_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_maestro_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_maestro_proto_rawDescGZIP(), []int{6}
}

func (x *CancelRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *CancelRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_pkg_proto_maestro_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_maestro_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_maestro_proto_rawDescGZIP(), []int{7}
}

func (x *CancelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Payload       *anypb.Any             `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CorrelationId string                 `protobuf:"bytes,4,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,5,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	StepId        string                 `protobuf:"bytes,6,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceRequest) Reset() {
	*x = ServiceRequest{}
	mi := &file_pkg_proto_maestro_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRequest) ProtoMessage() {}

func (x *ServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_maestro_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRequest.ProtoReflect.Descriptor instead.
func (*ServiceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_maestro_proto_rawDescGZIP(), []int{8}
}

func (x *ServiceRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ServiceRequest) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServiceRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ServiceRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ServiceRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *ServiceRequest) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

type ServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Data          *anypb.Any             `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceResponse) Reset() {
	*x = ServiceResponse{}
	mi := &file_pkg_proto_maestro_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceResponse) ProtoMessage() {}

func (x *ServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_maestro_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceResponse.ProtoReflect.Descriptor instead.
func (*ServiceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_maestro_proto_rawDescGZIP(), []int{9}
}

func (x *ServiceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ServiceResponse) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ServiceResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ServiceResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type HealthStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CheckedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthStatus) Reset() {
	*x = HealthStatus{}
	mi := &file_pkg_proto_maestro_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthStatus) ProtoMessage() {}

func (x *HealthStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_maestro_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthStatus.ProtoReflect.Descriptor instead.
func (*HealthStatus) Descriptor() ([]byte, []int) {
	return file_pkg_proto_maestro_proto_rawDescGZIP(), []int{10}
}

func (x *HealthStatus) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthStatus) GetCheckedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckedAt
	}
	return nil
}

type StepStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepId        string                 `protobuf:"bytes,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	State         StepState              `protobuf:"varint,2,opt,name=state,proto3,enum=maestro.v1.StepState" json:"state,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	RetryCount    int32                  `protobuf:"varint,6,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepStatus) Reset() {
	*x = StepStatus{}
	mi := &file_pkg_proto_maestro_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepStatus) ProtoMessage() {}

func (x *StepStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_maestro_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepStatus.ProtoReflect.Descriptor instead.
func (*StepStatus) Descriptor() ([]byte, []int) {
	return file_pkg_proto_maestro_proto_rawDescGZIP(), []int{11}
}

func (x *StepStatus) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *StepStatus) GetState() StepState {
	if x != nil {
		return x.State
	}
	return StepState_STEP_STATE_UNKNOWN
}

func (x *StepStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *StepStatus) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *StepStatus) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *StepStatus) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

var File_pkg_proto_maestro_proto protoreflect.FileDescriptor

const file_pkg_proto_maestro_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/proto/maestro.proto\x12\n" +
	"maestro.v1\x1a\x19google/protobuf/any.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\a\n" +
	"\x05Empty\"\x90\x02\n" +
	"\x0eExecuteRequest\x12#\n" +
	"\rworkflow_name\x18\x01 \x01(\tR\fworkflowName\x12-\n" +
	"\x05input\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x05input\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\x12D\n" +
	"\bmetadata\x18\x04 \x03(\v2(.maestro.v1.ExecuteRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa7\x02\n" +
	"\x0fExecuteResponse\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x122\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1a.maestro.v1.WorkflowStatusR\x06status\x12/\n" +
	"\x06output\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06output\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\xf4\x01\n" +
	"\fExecuteEvent\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x17\n" +
	"\astep_id\x18\x02 \x01(\tR\x06stepId\x12)\n" +
	"\x04type\x18\x03 \x01(\x0e2\x15.maestro.v1.EventTypeR\x04type\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12+\n" +
	"\x04data\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x04data\"0\n" +
	"\rStatusRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\"\xda\x01\n" +
	"\x0eStatusResponse\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x122\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1a.maestro.v1.WorkflowStatusR\x06status\x12,\n" +
	"\x05steps\x18\x03 \x03(\v2\x16.maestro.v1.StepStatusR\x05steps\x12/\n" +
	"\x06output\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x06output\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"H\n" +
	"\rCancelRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"D\n" +
	"\x0eCancelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb8\x02\n" +
	"\x0eServiceRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12.\n" +
	"\apayload\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\apayload\x12A\n" +
	"\aheaders\x18\x03 \x03(\v2'.maestro.v1.ServiceRequest.HeadersEntryR\aheaders\x12%\n" +
	"\x0ecorrelation_id\x18\x04 \x01(\tR\rcorrelationId\x12\x1f\n" +
	"\vworkflow_id\x18\x05 \x01(\tR\n" +
	"workflowId\x12\x17\n" +
	"\astep_id\x18\x06 \x01(\tR\x06stepId\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xef\x01\n" +
	"\x0fServiceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12(\n" +
	"\x04data\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x04data\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12E\n" +
	"\bmetadata\x18\x04 \x03(\v2).maestro.v1.ServiceResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"}\n" +
	"\fHealthStatus\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x129\n" +
	"\n" +
	"checked_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcheckedAt\"\x83\x02\n" +
	"\n" +
	"StepStatus\x12\x17\n" +
	"\astep_id\x18\x01 \x01(\tR\x06stepId\x12+\n" +
	"\x05state\x18\x02 \x01(\x0e2\x15.maestro.v1.StepStateR\x05state\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12\x1f\n" +
	"\vretry_count\x18\x06 \x01(\x05R\n" +
	"retryCount*\x82\x02\n" +
	"\x0eWorkflowStatus\x12\x1b\n" +
	"\x17WORKFLOW_STATUS_UNKNOWN\x10\x00\x12\x1b\n" +
	"\x17WORKFLOW_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17WORKFLOW_STATUS_RUNNING\x10\x02\x12\x1b\n" +
	"\x17WORKFLOW_STATUS_SUCCESS\x10\x03\x12\x1a\n" +
	"\x16WORKFLOW_STATUS_FAILED\x10\x04\x12\x1d\n" +
	"\x19WORKFLOW_STATUS_CANCELLED\x10\x05\x12 \n" +
	"\x1cWORKFLOW_STATUS_COMPENSATING\x10\x06\x12\x1f\n" +
	"\x1bWORKFLOW_STATUS_COMPENSATED\x10\a*\xd3\x01\n" +
	"\tStepState\x12\x16\n" +
	"\x12STEP_STATE_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12STEP_STATE_PENDING\x10\x01\x12\x16\n" +
	"\x12STEP_STATE_RUNNING\x10\x02\x12\x16\n" +
	"\x12STEP_STATE_SUCCESS\x10\x03\x12\x15\n" +
	"\x11STEP_STATE_FAILED\x10\x04\x12\x16\n" +
	"\x12STEP_STATE_SKIPPED\x10\x05\x12\x1b\n" +
	"\x17STEP_STATE_COMPENSATING\x10\x06\x12\x1a\n" +
	"\x16STEP_STATE_COMPENSATED\x10\a*\xc6\x02\n" +
	"\tEventType\x12\x16\n" +
	"\x12EVENT_TYPE_UNKNOWN\x10\x00\x12\x1f\n" +
	"\x1bEVENT_TYPE_WORKFLOW_STARTED\x10\x01\x12!\n" +
	"\x1dEVENT_TYPE_WORKFLOW_COMPLETED\x10\x02\x12\x1e\n" +
	"\x1aEVENT_TYPE_WORKFLOW_FAILED\x10\x03\x12\x1b\n" +
	"\x17EVENT_TYPE_STEP_STARTED\x10\x04\x12\x1d\n" +
	"\x19EVENT_TYPE_STEP_COMPLETED\x10\x05\x12\x1a\n" +
	"\x16EVENT_TYPE_STEP_FAILED\x10\x06\x12\x19\n" +
	"\x15EVENT_TYPE_STEP_RETRY\x10\a\x12#\n" +
	"\x1fEVENT_TYPE_COMPENSATION_STARTED\x10\b\x12%\n" +
	"!EVENT_TYPE_COMPENSATION_COMPLETED\x10\t2\xc0\x02\n" +
	"\fOrchestrator\x12J\n" +
	"\x0fExecuteWorkflow\x12\x1a.maestro.v1.ExecuteRequest\x1a\x1b.maestro.v1.ExecuteResponse\x12O\n" +
	"\x15ExecuteWorkflowStream\x12\x1a.maestro.v1.ExecuteRequest\x1a\x18.maestro.v1.ExecuteEvent0\x01\x12J\n" +
	"\x11GetWorkflowStatus\x12\x19.maestro.v1.StatusRequest\x1a\x1a.maestro.v1.StatusResponse\x12G\n" +
	"\x0eCancelWorkflow\x12\x19.maestro.v1.CancelRequest\x1a\x1a.maestro.v1.CancelResponse2\xd7\x01\n" +
	"\x0eMaestroService\x12B\n" +
	"\aExecute\x12\x1a.maestro.v1.ServiceRequest\x1a\x1b.maestro.v1.ServiceResponse\x12E\n" +
	"\n" +
	"Compensate\x12\x1a.maestro.v1.ServiceRequest\x1a\x1b.maestro.v1.ServiceResponse\x12:\n" +
	"\vHealthCheck\x12\x11.maestro.v1.Empty\x1a\x18.maestro.v1.HealthStatusB/Z-github.com/maestro/maestro.go/pkg/proto;protob\x06proto3"

var (
	file_pkg_proto_maestro_proto_rawDescOnce sync.Once
	file_pkg_proto_maestro_proto_rawDescData []byte
)

func file_pkg_proto_maestro_proto_rawDescGZIP() []byte {
	file_pkg_proto_maestro_proto_rawDescOnce.Do(func() {
		file_pkg_proto_maestro_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_maestro_proto_rawDesc), len(file_pkg_proto_maestro_proto_rawDesc)))
	})
	return file_pkg_proto_maestro_proto_rawDescData
}

var file_pkg_proto_maestro_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_pkg_proto_maestro_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_pkg_proto_maestro_proto_goTypes = []any{
	(WorkflowStatus)(0),           // 0: maestro.v1.WorkflowStatus
	(StepState)(0),                // 1: maestro.v1.StepState
	(EventType)(0),                // 2: maestro.v1.EventType
	(*Empty)(nil),                 // 3: maestro.v1.Empty
	(*ExecuteRequest)(nil),        // 4: maestro.v1.ExecuteRequest
	(*ExecuteResponse)(nil),       // 5: maestro.v1.ExecuteResponse
	(*ExecuteEvent)(nil),          // 6: maestro.v1.ExecuteEvent
	(*StatusRequest)(nil),         // 7: maestro.v1.StatusRequest
	(*StatusResponse)(nil),        // 8: maestro.v1.StatusResponse
	(*CancelRequest)(nil),         // 9: maestro.v1.CancelRequest
	(*CancelResponse)(nil),        // 10: maestro.v1.CancelResponse
	(*ServiceRequest)(nil),        // 11: maestro.v1.ServiceRequest
	(*ServiceResponse)(nil),       // 12: maestro.v1.ServiceResponse
	(*HealthStatus)(nil),          // 13: maestro.v1.HealthStatus
	(*StepStatus)(nil),            // 14: maestro.v1.StepStatus
	nil,                           // 15: maestro.v1.ExecuteRequest.MetadataEntry
	nil,                           // 16: maestro.v1.ServiceRequest.HeadersEntry
	nil,                           // 17: maestro.v1.ServiceResponse.MetadataEntry
	(*structpb.Struct)(nil),       // 18: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 19: google.protobuf.Timestamp
	(*anypb.Any)(nil),             // 20: google.protobuf.Any
}
var file_pkg_proto_maestro_proto_depIdxs = []int32{
	18, // 0: maestro.v1.ExecuteRequest.input:type_name -> google.protobuf.Struct
	15, // 1: maestro.v1.ExecuteRequest.metadata:type_name -> maestro.v1.ExecuteRequest.MetadataEntry
	0,  // 2: maestro.v1.ExecuteResponse.status:type_name -> maestro.v1.WorkflowStatus
	18, // 3: maestro.v1.ExecuteResponse.output:type_name -> google.protobuf.Struct
	19, // 4: maestro.v1.ExecuteResponse.started_at:type_name -> google.protobuf.Timestamp
	19, // 5: maestro.v1.ExecuteResponse.completed_at:type_name -> google.protobuf.Timestamp
	2,  // 6: maestro.v1.ExecuteEvent.type:type_name -> maestro.v1.EventType
	19, // 7: maestro.v1.ExecuteEvent.timestamp:type_name -> google.protobuf.Timestamp
	18, // 8: maestro.v1.ExecuteEvent.data:type_name -> google.protobuf.Struct
	0,  // 9: maestro.v1.StatusResponse.status:type_name -> maestro.v1.WorkflowStatus
	14, // 10: maestro.v1.StatusResponse.steps:type_name -> maestro.v1.StepStatus
	18, // 11: maestro.v1.StatusResponse.output:type_name -> google.protobuf.Struct
	20, // 12: maestro.v1.ServiceRequest.payload:type_name -> google.protobuf.Any
	16, // 13: maestro.v1.ServiceRequest.headers:type_name -> maestro.v1.ServiceRequest.HeadersEntry
	20, // 14: maestro.v1.ServiceResponse.data:type_name -> google.protobuf.Any
	17, // 15: maestro.v1.ServiceResponse.metadata:type_name -> maestro.v1.ServiceResponse.MetadataEntry
	19, // 16: maestro.v1.HealthStatus.checked_at:type_name -> google.protobuf.Timestamp
	1,  // 17: maestro.v1.StepStatus.state:type_name -> maestro.v1.StepState
	19, // 18: maestro.v1.StepStatus.started_at:type_name -> google.protobuf.Timestamp
	19, // 19: maestro.v1.StepStatus.completed_at:type_name -> google.protobuf.Timestamp
	4,  // 20: maestro.v1.Orchestrator.ExecuteWorkflow:input_type -> maestro.v1.ExecuteRequest
	4,  // 21: maestro.v1.Orchestrator.ExecuteWorkflowStream:input_type -> maestro.v1.ExecuteRequest
	7,  // 22: maestro.v1.Orchestrator.GetWorkflowStatus:input_type -> maestro.v1.StatusRequest
	9,  // 23: maestro.v1.Orchestrator.CancelWorkflow:input_type -> maestro.v1.CancelRequest
	11, // 24: maestro.v1.MaestroService.Execute:input_type -> maestro.v1.ServiceRequest
	11, // 25: maestro.v1.MaestroService.Compensate:input_type -> maestro.v1.ServiceRequest
	3,  // 26: maestro.v1.MaestroService.HealthCheck:input_type -> maestro.v1.Empty
	5,  // 27: maestro.v1.Orchestrator.ExecuteWorkflow:output_type -> maestro.v1.ExecuteResponse
	6,  // 28: maestro.v1.Orchestrator.ExecuteWorkflowStream:output_type -> maestro.v1.ExecuteEvent
	8,  // 29: maestro.v1.Orchestrator.GetWorkflowStatus:output_type -> maestro.v1.StatusResponse
	10, // 30: maestro.v1.Orchestrator.CancelWorkflow:output_type -> maestro.v1.CancelResponse
	12, // 31: maestro.v1.MaestroService.Execute:output_type -> maestro.v1.ServiceResponse
	12, // 32: maestro.v1.MaestroService.Compensate:output_type -> maestro.v1.ServiceResponse
	13, // 33: maestro.v1.MaestroService.HealthCheck:output_type -> maestro.v1.HealthStatus
	27, // [27:34] is the sub-list for method output_type
	20, // [20:27] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_pkg_proto_maestro_proto_init() }
func file_pkg_proto_maestro_proto_init() {
	if File_pkg_proto_maestro_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_maestro_proto_rawDesc), len(file_pkg_proto_maestro_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pkg_proto_maestro_proto_goTypes,
		DependencyIndexes: file_pkg_proto_maestro_proto_depIdxs,
		EnumInfos:         file_pkg_proto_maestro_proto_enumTypes,
		MessageInfos:      file_pkg_proto_maestro_proto_msgTypes,
	}.Build()
	File_pkg_proto_maestro_proto = out.File
	file_pkg_proto_maestro_proto_goTypes = nil
	file_pkg_proto_maestro_proto_depIdxs = nil
}
